# Terragon Autonomous SDLC Configuration
# Repository: WASM Shim for Torch
# Maturity Level: ADVANCED (89/100)

# Value Discovery Configuration
scoring:
  # Adaptive weights based on ADVANCED repository maturity
  weights:
    wsjf: 0.5        # Weighted Shortest Job First
    ice: 0.1         # Impact × Confidence × Ease
    technicalDebt: 0.3  # Technical debt impact
    security: 0.1    # Security vulnerability boost
  
  # Scoring thresholds and multipliers
  thresholds:
    minScore: 15           # Minimum composite score for execution
    maxRisk: 0.8          # Maximum risk tolerance
    securityBoost: 2.0    # Security vulnerability multiplier
    complianceBoost: 1.8  # Compliance issue multiplier
    debtInterestRate: 0.15 # Technical debt growth rate

# Value Discovery Sources
discovery:
  sources:
    - gitHistory          # Parse commit messages and TODOs
    - staticAnalysis      # Code quality and complexity analysis
    - issueTrackers      # GitHub issues and discussions
    - vulnerabilityDatabases  # CVE and security advisories
    - performanceMonitoring   # Regression detection
    - dependencyUpdates  # Package update availability
  
  # Analysis tools configuration
  tools:
    staticAnalysis:
      - ruff             # Python linting (already configured)
      - mypy             # Type checking (already configured)
      - bandit           # Security analysis (already configured)
      - complexity       # Cyclomatic complexity analysis
    security:
      - pip-audit        # Python dependency vulnerabilities
      - safety           # Security vulnerability scanning
      - semgrep          # Static analysis security testing
    performance:
      - pytest-benchmark # Performance regression testing
      - memory-profiler  # Memory usage analysis
    quality:
      - sonarqube-community # Code quality analysis
      - codeclimate      # Maintainability metrics

# Autonomous Execution Configuration
execution:
  maxConcurrentTasks: 1    # Execute one task at a time
  executionSchedule:
    immediate: true        # Execute after PR merge
    hourly: true          # Hourly security scans
    daily: true           # Daily comprehensive analysis
    weekly: true          # Weekly deep assessment
    monthly: true         # Monthly strategic review
  
  # Quality gates for execution
  testRequirements:
    minCoverage: 80       # Minimum test coverage percentage
    performanceRegression: 5  # Max % performance degradation
    securityThreshold: 0  # Zero critical vulnerabilities
  
  # Automatic rollback triggers
  rollbackTriggers:
    - testFailure
    - buildFailure
    - securityViolation
    - performanceRegression

# Repository-Specific Configuration
repository:
  name: "wasm-shim-torch"
  maturityLevel: "ADVANCED"
  maturityScore: 89
  primaryLanguage: "python"
  frameworks:
    - pytorch
    - webassembly
    - emscripten
  
  # Key directories for analysis
  keyDirectories:
    source: ["src/", "runtime/"]
    tests: ["tests/"]
    docs: ["docs/", "README.md"]
    config: ["pyproject.toml", "CMakeLists.txt"]
    scripts: ["scripts/"]

# Learning and Adaptation
learning:
  # Track prediction accuracy
  accuracyTracking:
    effortEstimation: true
    impactPrediction: true
    valueDelivery: true
  
  # Model adaptation parameters
  adaptationRate: 0.1     # Learning rate for model updates
  confidenceThreshold: 0.7 # Minimum confidence for predictions
  feedbackWindow: 30      # Days to collect execution feedback

# Notification and Reporting
notifications:
  channels:
    - github-issues      # Create GitHub issues for high-value items
    - pull-requests      # Automated PR creation
    - project-boards     # Update project boards
  
  reporting:
    backlogUpdate: true   # Maintain BACKLOG.md
    metricsTracking: true # Track value delivery metrics
    learningReports: true # Generate learning summaries

# Integration Configuration
integrations:
  github:
    enabled: true
    autoCreatePRs: true
    labelStrategy: "value-driven"
    assignCodeOwners: true
  
  monitoring:
    prometheus: false    # Not yet configured
    grafana: false       # Not yet configured
    datadog: false       # Not yet configured
  
  security:
    snyk: false          # Not yet configured
    dependabot: true     # Already configured
    codeql: false        # Not yet configured